import React from 'react';

const Home = () => {
  return (
    <div>   
      {/* Conteúdo Principal */}
      <div style={{ textAlign: 'center', padding: '20px' }}>
        <h1>Bem-vindo à Biblioteca</h1>
        <p>Explore nosso acervo e descubra um mundo de conhecimento e aventuras.</p>
        <button 
          style={{
            padding: '10px 20px',
            fontSize: '16px',
            backgroundColor: '#007BFF',
            color: '#fff',
            border: 'none',
            borderRadius: '5px',
            cursor: 'pointer'
          }}
          onClick={() => alert('Explorando o acervo!')}
        >
          Explorar Livros
        </button>
        {/* <div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero repudiandae quam ratione consequuntur, beatae doloribus, ipsam, dignissimos reiciendis temporibus et corrupti eos? Omnis doloremque quod distinctio inventore esse qui dicta.</div>
        </div> */}
      </div>
    </div>
  );
};

export default Home;